# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import llm_pb2 as llm__pb2


class CoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/llmmcp.v1.Core/SubmitJob',
                request_serializer=llm__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=llm__pb2.SubmitJobResponse.FromString,
                )
        self.GetJob = channel.unary_unary(
                '/llmmcp.v1.Core/GetJob',
                request_serializer=llm__pb2.GetJobRequest.SerializeToString,
                response_deserializer=llm__pb2.GetJobResponse.FromString,
                )
        self.StreamJob = channel.unary_stream(
                '/llmmcp.v1.Core/StreamJob',
                request_serializer=llm__pb2.StreamJobRequest.SerializeToString,
                response_deserializer=llm__pb2.JobEvent.FromString,
                )
        self.RegisterWorker = channel.unary_unary(
                '/llmmcp.v1.Core/RegisterWorker',
                request_serializer=llm__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=llm__pb2.RegisterWorkerResponse.FromString,
                )
        self.ClaimJob = channel.unary_unary(
                '/llmmcp.v1.Core/ClaimJob',
                request_serializer=llm__pb2.ClaimJobRequest.SerializeToString,
                response_deserializer=llm__pb2.ClaimJobResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/llmmcp.v1.Core/Heartbeat',
                request_serializer=llm__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=llm__pb2.HeartbeatResponse.FromString,
                )
        self.CompleteJob = channel.unary_unary(
                '/llmmcp.v1.Core/CompleteJob',
                request_serializer=llm__pb2.CompleteJobRequest.SerializeToString,
                response_deserializer=llm__pb2.CompleteJobResponse.FromString,
                )
        self.FailJob = channel.unary_unary(
                '/llmmcp.v1.Core/FailJob',
                request_serializer=llm__pb2.FailJobRequest.SerializeToString,
                response_deserializer=llm__pb2.FailJobResponse.FromString,
                )
        self.ReportMetrics = channel.unary_unary(
                '/llmmcp.v1.Core/ReportMetrics',
                request_serializer=llm__pb2.ReportMetricsRequest.SerializeToString,
                response_deserializer=llm__pb2.ReportMetricsResponse.FromString,
                )
        self.ReportBenchmark = channel.unary_unary(
                '/llmmcp.v1.Core/ReportBenchmark',
                request_serializer=llm__pb2.ReportBenchmarkRequest.SerializeToString,
                response_deserializer=llm__pb2.ReportBenchmarkResponse.FromString,
                )


class CoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBenchmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=llm__pb2.SubmitJobRequest.FromString,
                    response_serializer=llm__pb2.SubmitJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=llm__pb2.GetJobRequest.FromString,
                    response_serializer=llm__pb2.GetJobResponse.SerializeToString,
            ),
            'StreamJob': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJob,
                    request_deserializer=llm__pb2.StreamJobRequest.FromString,
                    response_serializer=llm__pb2.JobEvent.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=llm__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=llm__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'ClaimJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimJob,
                    request_deserializer=llm__pb2.ClaimJobRequest.FromString,
                    response_serializer=llm__pb2.ClaimJobResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=llm__pb2.HeartbeatRequest.FromString,
                    response_serializer=llm__pb2.HeartbeatResponse.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=llm__pb2.CompleteJobRequest.FromString,
                    response_serializer=llm__pb2.CompleteJobResponse.SerializeToString,
            ),
            'FailJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FailJob,
                    request_deserializer=llm__pb2.FailJobRequest.FromString,
                    response_serializer=llm__pb2.FailJobResponse.SerializeToString,
            ),
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=llm__pb2.ReportMetricsRequest.FromString,
                    response_serializer=llm__pb2.ReportMetricsResponse.SerializeToString,
            ),
            'ReportBenchmark': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBenchmark,
                    request_deserializer=llm__pb2.ReportBenchmarkRequest.FromString,
                    response_serializer=llm__pb2.ReportBenchmarkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmmcp.v1.Core', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Core(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/SubmitJob',
            llm__pb2.SubmitJobRequest.SerializeToString,
            llm__pb2.SubmitJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/GetJob',
            llm__pb2.GetJobRequest.SerializeToString,
            llm__pb2.GetJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/llmmcp.v1.Core/StreamJob',
            llm__pb2.StreamJobRequest.SerializeToString,
            llm__pb2.JobEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/RegisterWorker',
            llm__pb2.RegisterWorkerRequest.SerializeToString,
            llm__pb2.RegisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClaimJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/ClaimJob',
            llm__pb2.ClaimJobRequest.SerializeToString,
            llm__pb2.ClaimJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/Heartbeat',
            llm__pb2.HeartbeatRequest.SerializeToString,
            llm__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/CompleteJob',
            llm__pb2.CompleteJobRequest.SerializeToString,
            llm__pb2.CompleteJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FailJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/FailJob',
            llm__pb2.FailJobRequest.SerializeToString,
            llm__pb2.FailJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/ReportMetrics',
            llm__pb2.ReportMetricsRequest.SerializeToString,
            llm__pb2.ReportMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportBenchmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/llmmcp.v1.Core/ReportBenchmark',
            llm__pb2.ReportBenchmarkRequest.SerializeToString,
            llm__pb2.ReportBenchmarkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
