name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / traces
